server:
  port: 8081

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/


spring:
 application:
   name: order-service
 boot:
   admin:
     client:
       url: http://localhost:8088/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
